<a href="https://colab.research.google.com/github/mdmasoomcse/TNS-prcatice-sessions/blob/main/TNS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
list1=[]
a=list1.append(input("Enter 1 movie name"))
b=list1.append(input("Enter 2 movie name"))
c=list1.append(input("Enter 3 movie name"))
d=list1.append(input("Enter 4 movie name"))
print(list1)

Enter 1 movie nameRRR
Enter 2 movie nameRagghvarun
Enter 3 movie nameBahu
Enter 4 movie nameMaharshi
['RRR', 'Ragghvarun', 'Bahu', 'Maharshi']


In [ ]:
#check palindrome
list1=[1,2,3]
copy_list1=list1.copy()
copy_list1.reverse()

if list1==copy_list1:
  print("It is palindrome!!")
else:
    print("Not a palindrome")

Not a palindrome


In [ ]:
grade=("C","D","A","A","B","B","A")
print(grade.count("A"))

3


In [ ]:
grade=["C","D","A","A","B","B","A"]
grade.sort()
print(grade)

['A', 'A', 'A', 'B', 'B', 'C', 'D']


In [ ]:
#Dictionaries--
dict={
    "name":"masoom",
    "cgpa":7.8,
    "college":"JNTUH",
    "skills":["Web developer","Data analytics","QA"]
}
print(dict["skills"])
print(dict)
new_dict={}
new_dict["age"]=22
print(new_dict)

['Web developer', 'Data analytics', 'QA']
{'name': 'masoom', 'cgpa': 7.8, 'college': 'JNTUH', 'skills': ['Web developer', 'Data analytics', 'QA']}
{'age': 22}


In [ ]:
#nested dictionary--
new_dict={
    "name":"masoom",
    "subject":{
        "phy":22,
        "chem":23,
        "math":24
    }
}
print(new_dict["subject"])
print(new_dict["subject"]["math"])

{'phy': 22, 'chem': 23, 'math': 24}
24


In [ ]:
#methods-
#dict.keys()
#values()
#items()
#get()
#update(newdict)

dict={
    "name":"masoom",
    "cgpa":7.8,
    "college":"JNTUH",
    "skills":["Web developer","Data analytics","QA"]
}
print(dict.keys())
print(dict.values())
print(dict.items())


dict_keys(['name', 'cgpa', 'college', 'skills'])
dict_values(['masoom', 7.8, 'JNTUH', ['Web developer', 'Data analytics', 'QA']])
dict_items([('name', 'masoom'), ('cgpa', 7.8), ('college', 'JNTUH'), ('skills', ['Web developer', 'Data analytics', 'QA'])])


In [ ]:
#sets--ignore duplicate values
#set.add(el)
#set.remove(el)
#set.clear()
#set.pop()
collection={1,2,3,4,5,6,7,8,9}
print(collection)
print(type(collection))




{1, 2, 3, 4, 5, 6, 7, 8, 9}
<class 'set'>


In [ ]:
#practice
collection=set()

collection.add(20)
print(collection)
collection.add(40)
print(collection)
collection.remove(20)
print(collection)
print(collection.pop())

meanings={
    "table":["a beautiful furniture","list of facts and furniture"],
    "cat":"is a small animal"

}
print(meanings)
#######
set1={"python","c++","python","javasrcipt","java","python","java","c++","c"}
print(type(set1))
print(len(set1))


{20}
{40, 20}
{40}
40
{'table': ['a beautiful furniture', 'list of facts and furniture'], 'cat': 'is a small animal'}
<class 'set'>
5


In [ ]:
subjects={
    "math":int(input("Enter math marks")),
    "social":int(input("Enter social subject marks")),
    "science":int(input("Enter science subject marks")),
    "english":int(input("Enter english subject marks")),
    "geography":int(input("Enter geography subject marks")),
}
print(subjects)

######
num={
    "a":[int(input("Enter 1st number")),float(input("Enter 2nd number"))],

}
print(num)

Enter math marks54
Enter social subject marks88
Enter science subject marks25
Enter english subject marks77
Enter geography subject marks98
{'math': 54, 'social': 88, 'science': 25, 'english': 77, 'geography': 98}
Enter 1st number9
Enter 2nd number9.0
{'a': [9, 9.0]}


In [ ]:
def sum(a,b):
  return a+b
c=sum(10,22)
print(c)

32


In [ ]:
def print_hello():
  print("Hello")
print_hello()

Hello


In [ ]:
def avg(a,b,c):
  return (a+b+c)/3
num=avg(1,2,3)
print(num)

2.0


In [ ]:
def numbers(a,b):
  return a*b
c=numbers(int(input("enter number")),int(input("enter number")))
print(c)

enter number44
enter number55
2420


In [ ]:
def currency(a):
  return a*97
b=currency(int(input("Enter your Indian Currency--")))
print("USA Value:",b)


Enter your Indian Currency--55
USA Value: 5335


In [ ]:
def num(a):
  if a%2==0:
    print("you entered number is Even!!")
  else:
    print("you enter number is Odd!!")

cat=num(int(input("Enter number")))


Enter number4
you entered number is Even!!


In [ ]:
name=["ravi","rajesh","srikanth","das"]
def count_list():
  a=print(len(name))

print(count_list())


4
None


In [ ]:
def factorial(n):
    if n == 1:
        return 1
    return n * factorial(n-1)

print(factorial(9))

362880


In [ ]:
def assign_num(a,b):
  if (a+b)>10:
    print("Welcome!!")
  else:
    print("Login Successfull!!")
assign_num(int(input("Enter number 1-")),int(input("Enter number2-")))


Enter number 1-5
Enter number2-2
Login Successfull!!


In [ ]:
#oop class and instances(or)objects
class Student:
  name="mohammed"
s1=Student()
print(s1.name)

mohammed


In [ ]:
class Car:
  color="Blue"
  brand="toyota"

car1=Car()
print(car1.color)
print(car1.brand)

Blue
toyota


In [ ]:

#constructor
#default constructor
#def __init__(self)
#pass
#parameterized constructor
#def __init__(self,name,age,class)

class Student:
  def __init__(self,fullname,age,Degree):
    self.name=fullname
    self.a=age
    self.D=Degree


s1=Student("masoom",24,"Engg")
print(s1.name)
print(s1.a)
print(s1.D)

s2=Student("rabi",33,"Doctor")
print(s2.name)
print(s2.a)

masoom
24
Engg
rabi
33


In [ ]:
#class & instance
#class attributes and object attributes
#obj attrributes>class attributes
class Company:
  org_name="TNS"  #class atrributes

  def __init__(self,Emp_name,Emp_Id,Emp_age):
    #obijet attributes
    self.Emp_name=Emp_name
    self.Emp_Id=Emp_Id
    self.Emp_age=Emp_age

e1=Company("rohith",223,22)
print(e1.Emp_age)
print(Company.org_name)







22
TNS


In [ ]:
#write a program the takes name,and 3 numbers and print the average of three numbers within the function using class and objects

class Student():
  def __init__(self,name,sub1,sub2,sub3):
    self.name=name
    self.sub1=sub1
    self.sub2=sub2
    self.sub3=sub3

s1=Student("Ravi",33,45,90)
s2=(s1.name)
s3=(s1.sub1)+(s1.sub2)+(s1.sub3)
print(s2)
print(s3/3)

Ravi
56.0


In [ ]:
                                                #NUMPY library PRACTICE::

#CREATION OF ARRAY
import numpy as np
arr=np.array([1,2,3,4,])
arr1=np.array([5,6,7,8])
print(arr)

maximum=np.max(arr)
print(maximum)

minimum=np.min(arr)
print(minimum)

mean=np.mean(arr)
print(mean)

median=np.median(arr)
print(median)

var=np.var(arr)
print(var)

std=np.std(arr)
print(std)

a=np.eye(2,2)
print(a)

linsp=np.linspace(1,10,5)
print(linsp)

range=np.arange(1,10,2)
print(range)

resh=np.reshape(arr,(2,2))
print(resh)


agr=np.argmax(arr)
print(agr)

agr1=np.argmin(arr1)
print(agr1)

mul=np.multiply(arr,arr1)
print(mul)

[1 2 3 4]
4
1
2.5
2.5
1.25
1.118033988749895
[[1. 0.]
 [0. 1.]]
[ 1.    3.25  5.5   7.75 10.  ]
[1 3 5 7 9]
[[1 2]
 [3 4]]
3
0
[ 5 12 21 32]


In [ ]:
                              #shape and axis manipulation
import numpy as np
arr=np.array([1,2,3,4,5])
arr1=np.arange(1,13) # Changed to create 12 elements
print(arr1)

a=arr1.reshape(4,3)
print(a)
b=arr1.transpose()
print(b)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [ ]:

                                    #TASK::15-06-2026
import numpy as np
marks=([65,78,90,55,88])
#AVERAGE OF MARKS
avg=np.average(marks)
print(avg)
#HIGHEST MARKS
max=np.max(marks)
print(max)
#LOWEST MARKS
min=np.min(marks)
print(min)

75.2
90
55


In [ ]:
import numpy as np
arr=np.arange(1,21)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [ ]:
import numpy as np
arr1=np.arange(2,21,2)
print(arr1)

[ 2  4  6  8 10 12 14 16 18 20]


In [ ]:
import numpy as np
array1=np.arange(1,11)
sum=np.sum(array1)
print(sum)

avg=np.average(array1)
print(avg)

max=np.max(array1)
print(max)

min=np.min(array1)
print(min)

55
5.5
10
1


PANDAS PRACTICE SESSIONS

In [ ]:
import pandas as pd
panda=pd.Series([1,2,3,4,5,6])
print(panda)


0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64


In [ ]:
import pandas as pd
panda=pd.Series([1,2,3,4,5,6])
print(panda.count)

sorting=panda.sort_values()
print(sorting)

slicing=panda[0:3]
print(slicing)

filter=panda[panda>3]
print(filter)

location=panda.loc[3]
print(location)

index=panda.iloc[-2]
print(index)

drop=panda.drop(3)
print(drop)

sum=panda.sum()
print(sum)

avg=panda.mean()
print(avg)

max=panda.max()
print(max)

min=panda.min()
print(min)


cum_sum=panda.cumsum()
print(cum_sum)

sum=panda.sum()
print(sum)

panda1=pd.Series([10,20,50,None,77,82])

null_1=panda.isnull()
print(null_1)

null_2=panda.notnull()
print(null_2)

mapping=panda.map({1:"one",2:"two",3:"three",4:"Four",5:"five",6:"six"})
print(mapping)

panda1.apply(lambda x: x * 2)


<bound method Series.count of 0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64>
0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64
0    1
1    2
2    3
dtype: int64
3    4
4    5
5    6
dtype: int64
4
5
0    1
1    2
2    3
4    5
5    6
dtype: int64
21
3.5
6
1
0     1
1     3
2     6
3    10
4    15
5    21
dtype: int64
21
0    False
1    False
2    False
3    False
4    False
5    False
dtype: bool
0    True
1    True
2    True
3    True
4    True
5    True
dtype: bool
0      one
1      two
2    three
3     Four
4     five
5      six
dtype: object


In [ ]:
import pandas as pd
data={
    "Team":["CSK","MI","RCB","LSG","DC","SRH","RR"],
    "CAPTAINS":["Ruturaj","Hardik Pandya","paditar","Rishabh pant","KL Rahul","Pat Cummins", "Sanju Samson"],
    "cups":[5,5,2,0,1,2,0],

}
arr=pd.DataFrame(data)
print(arr)

data1={
    "Team":["CSK","MI","RCB","LSG","DC","SRH","RR"],
    "CAPTAINS":["Ruturaj","Hardik Pandya","paditar","Rishabh pant","KL Rahul","Pat Cummins", "Sanju Samson"],

}

# arr=pd.DataFrame(data1)
# print(arr)

# arr.head()


# arr.tail()

merged_aarr=pd.merge(pd.DataFrame(data1),pd.DataFrame(data),on=["CAPTAINS","Team"])
print(merged_aarr)

  Team       CAPTAINS  cups
0  CSK        Ruturaj     5
1   MI  Hardik Pandya     5
2  RCB        paditar     2
3  LSG   Rishabh pant     0
4   DC       KL Rahul     1
5  SRH    Pat Cummins     2
6   RR   Sanju Samson     0
  Team       CAPTAINS  cups
0  CSK        Ruturaj     5
1   MI  Hardik Pandya     5
2  RCB        paditar     2
3  LSG   Rishabh pant     0
4   DC       KL Rahul     1
5  SRH    Pat Cummins     2
6   RR   Sanju Samson     0


In [ ]:
import pandas as pd
data={
    "animal":["dog","cat","horse","camel","snake","cat"],
    "type":["mammal","mammal","mammal","mammel","reptile","Cat"],
    "numbers":[1,2,3,4,5]
}
data1={
    "animal":["dog","cat","horse","camel","snake","cat"],
    "type":["mammal","reptile","mammal","mammel","reptile","fox"],
    "numbers":[1,2,3,4,5]
}
# fr=pd.DataFrame(data)
# print(fr)

# fr1=pd.DataFrame(data1)
# print(fr1)

merged_fr=pd.merge(fr,fr1,on=["animal","type"])
print(merged_fr)

cocat=pd.concat([fr,fr1])
print(cocat)


  animal     type  numbers_x  numbers_y
0    dog   mammal          1          1
1  horse   mammal          3          3
2  camel   mammel          4          4
3  snake  reptile          5          5
  animal     type  numbers
0    dog   mammal        1
1    cat   mammal        2
2  horse   mammal        3
3  camel   mammel        4
4  snake  reptile        5
0    dog   mammal        1
1    cat  reptile        2
2  horse   mammal        3
3  camel   mammel        4
4  snake  reptile        5


In [ ]:
from google.colab import files
uploaded=files.upload()

Saving customers-100.csv to customers-100.csv


In [ ]:
import pandas as pd
data={
    "numbers":[1,2,3,4,5,6,7,8,9],
}
data_frame=pd.DataFrame(data)
print(data_frame)

mean=data_frame["numbers"].mean()
print("your mean",mean)

sum=data_frame["numbers"].sum()
print("your sum is:",sum)

   numbers
0        1
1        2
2        3
3        4
4        5
5        6
6        7
7        8
8        9
your mean 5.0
your sum is: 45


In [ ]:
hospital={
    "Patient_id":[501,502,503,507,504,509],
    "Name":["rajesh","Ravi","koushik","nandu","satwik","sai"],
    "Age":[14,52,14,32,22, None], # Added None to make its length 6
    "Diesease":["typhoid","malaria","dengue","mental_illness","dipression","HIV"],
    "Days-Admitted":[5,40,7,7,9,10],
}
data_frame=pd.DataFrame(hospital)
print(data_frame)

duplicate_mask=data_frame['Days-Admitted'].duplicated()
print("Duplicates in 'Days-Admitted' column:", duplicate_mask)

add_dataframe=pd.DataFrame({"cost_per_day in thousand":[5,12,55,75,55,12]})
print(add_dataframe)

merged_df=pd.concat([data_frame,add_dataframe],axis=1)
print(merged_df)

# mean=data_frame["add_dataframe"].mean()
# print("your mean",mean)

sum_cost=merged_df["cost_per_day in thousand"].sum()
print("your sum is:",sum_cost)

avg_cost=merged_df["cost_per_day in thousand"].mean()
print(avg_cost)

max=merged_df["cost_per_day in thousand"].max()
print(max)

min=merged_df["cost_per_day in thousand"].min()
print(min)

   Patient_id     Name   Age        Diesease  Days-Admitted
0         501   rajesh  14.0         typhoid              5
1         502     Ravi  52.0         malaria             40
2         503  koushik  14.0          dengue              7
3         507    nandu  32.0  mental_illness              7
4         504   satwik  22.0      dipression              9
5         509      sai   NaN             HIV             10
Duplicates in 'Days-Admitted' column: 0    False
1    False
2    False
3     True
4    False
5    False
Name: Days-Admitted, dtype: bool
   cost_per_day in thousand
0                         5
1                        12
2                        55
3                        75
4                        55
5                        12
   Patient_id     Name   Age        Diesease  Days-Admitted  \
0         501   rajesh  14.0         typhoid              5   
1         502     Ravi  52.0         malaria             40   
2         503  koushik  14.0          dengue              